country_code_to_name = {
    'ad': 'principality of andorra',
    'ae': 'united arab emirates',
    'af': 'afghanistan',
    'ag': 'antigua',
    'ai': 'anguilla',
    'al': 'albania',
    'am': 'armenia',
    'an': 'netherlands antilles',
    'ao': 'angola',
    'aq': 'antarctica',
    'ar': 'argentina',
    'as': 'american samoa',
    'at': 'austria',
    'au': 'australia',
    'aw': 'aruba',
    'az': 'azerbaidjan',
    'ba': 'bosnia-herzegovina',
    'bb': 'barbados',
    'bd': 'bangladesh',
    'be': 'belgium',
    'bf': 'burkina faso',
    'bg': 'bulgaria',
    'bh': 'bahrain',
    'bi': 'burundi',
    'bj': 'benin',
    'bm': 'bermuda',
    'bn': 'brunei darussalam',
    'bo': 'bolivia',
    'br': 'brazil',
    'bs': 'bahamas',
    'bt': 'bhutan',
    'bv': 'bouvet island',
    'bw': 'botswana',
    'by': 'belarus',
    'bz': 'belize',
    'ca': 'canada',
    'cc': 'cocos islands',
    'cf': 'central african republic',
    'cd': 'the democratic republic of the congo',
    'cg': 'congo',
    'ch': 'switzerland',
    'ci': 'ivory coast',
    'ck': 'cook islands',
    'cl': 'chile',
    'cm': 'cameroon',
    'cn': 'china',
    'co': 'colombia',
    'cr': 'costa rica',
    'cu': 'cuba',
    'cv': 'cape verde',
    'cx': 'christmas island',
    'cy': 'cyprus',
    'cz': 'czech republic',
    'de': 'germany',
    'dj': 'djibouti',
    'dk': 'denmark',
    'dm': 'dominica',
    'do': 'dominican republic',
    'dz': 'algeria',
    'ec': 'ecuador',
    'ee': 'estonia',
    'eg': 'egypt',
    'eh': 'western sahara',
    'er': 'eritrea',
    'es': 'spain',
    'et': 'ethiopia',
    'fi': 'finland',
    'fj': 'fiji',
    'fk': 'falkland islands',
    'fm': 'micronesia',
    'fo': 'faroe islands',
    'fr': 'france',
    'ga': 'gabon',
    'gb': 'great britain',
    'gd': 'grenada',
    'ge': 'georgia',
    'gf': 'french guiana',
    'gh': 'ghana',
    'gi': 'gibraltar',
    'gl': 'greenland',
    'gm': 'gambia',
    'gn': 'guinea',
    'gp': 'guadeloupe',
    'gq': 'equatorial guinea',
    'gr': 'greece',
    'gt': 'guatemala',
    'gu': 'guam',
    'gw': 'guinea bissau',
    'gy': 'guiana',
    'hk': 'hong kong',
    'hm': 'heard and mcdonald islands',
    'hn': 'honduras',
    'hr': 'croatia',
    'ht': 'haiti',
    'hu': 'hungary',
    'id': 'indonesia',
    'ie': 'ireland',
    'il': 'israel',
    'in': 'india',
    'io': 'british indian ocean territory',
    'iq': 'iraq',
    'ir': 'iran',
    'is': 'iceland',
    'it': 'italy',
    'jm': 'jamaica',
    'jo': 'jordan',
    'jp': 'japan',
    'ke': 'kenya',
    'kg': 'kyrgyzstan',
    'kh': 'cambodia',
    'ki': 'kiribati',
    'km': 'comoros',
    'kn': 'saint kitts & nevis anguilla',
    'kp': 'north korea',
    'kr': 'south korea',
    'kw': 'kuwait',
    'ky': 'cayman islands',
    'kz': 'kazakhstan',
    'la': 'laos',
    'lb': 'lebanon',
    'lc': 'saint lucia',
    'li': 'liechtenstein',
    'lk': 'sri lanka',
    'lr': 'liberia',
    'ls': 'lesotho',
    'lt': 'lithuania',
    'lu': 'luxembourg',
    'lv': 'latvia',
    'ly': 'libya',
    'ma': 'morocco',
    'mc': 'monaco',
    'md': 'moldavia',
    'mg': 'madagascar',
    'mh': 'marshall islands',
    'mk': 'macedonia',
    'ml': 'mali',
    'mm': 'myanmar',
    'mn': 'mongolia',
    'mo': 'macau',
    'mp': 'northern mariana islands',
    'mq': 'martinique',
    'mr': 'mauritania',
    'ms': 'montserrat',
    'mt': 'malta',
    'mu': 'mauritius',
    'mv': 'maldives',
    'mw': 'malawi',
    'mx': 'mexico',
    'my': 'malaysia',
    'mz': 'mozambique',
    'na': 'namibia',
    'nc': 'new caledonia',
    'ne': 'niger',
    'nf': 'norfolk island',
    'ng': 'nigeria',
    'ni': 'nicaragua',
    'nl': 'netherlands',
    'no': 'norway',
    'np': 'nepal',
    'nr': 'nauru',
    'nt': 'neutral zone',
    'nu': 'niue',
    'nz': 'new zealand',
    'om': 'oman',
    'pa': 'panama',
    'pe': 'peru',
    'pf': 'french polynesia',
    'pg': 'papua new guinea',
    'ph': 'philippines',
    'pk': 'pakistan',
    'pl': 'poland',
    'pm': 'saint pierre and miquelon',
    'pn': 'pitcairn island',
    'pr': 'puerto rico',
    'pt': 'portugal',
    'pw': 'palau',
    'py': 'paraguay',
    'qa': 'qatar',
    're': 'reunion',
    'ro': 'romania',
    'ru': 'russian federation',
    'rw': 'rwanda',
    'sa': 'saudi arabia',
    'sb': 'solomon islands',
    'sc': 'seychelles',
    'sd': 'sudan',
    'se': 'sweden',
    'sg': 'singapore',
    'sh': 'saint helena',
    'si': 'slovenia',
    'sj': 'svalbard and jan mayen islands',
    'sk': 'slovak republic',
    'sl': 'sierra leone',
    'sm': 'san marino',
    'sn': 'senegal',
    'so': 'somalia',
    'sr': 'suriname',
    'sv': 'el salvador',
    'sy': 'syria',
    'sz': 'swaziland',
    'td': 'chad',
    'tf': 'french southern territories',
    'tg': 'togo',
    'th': 'thailand',
    'tj': 'tadjikistan',
    'tk': 'tokelau',
    'tm': 'turkmenistan',
    'tn': 'tunisia',
    'to': 'tonga',
    'tp': 'east timor',
    'tr': 'turkey',
    'tv': 'tuvalu',
    'tw': 'taiwan',
    'tz': 'tanzania',
    'ua': 'ukraine',
    'ug': 'uganda',
    'uk': 'united kingdom',
    'us': 'united states',
    'uy': 'uruguay',
    'uz': 'uzbekistan',
    'va': 'holy see',
    've': 'venezuela',
    'vg': 'british virgin islands',
    'vi': 'us virgin islands',
    'vn': 'vietnam',
    'vu': 'vanuatu',
    'wf': 'wallis and futuna islands',
    'ws': 'samoa',
    'ye': 'yemen',
    'yt': 'mayotte',
    'yu': 'yugoslavia',
    'za': 'south africa',
    'zm': 'zambia',
    'zr': 'zaire',
    'zw': 'zimbabwe'
}

country_name_to_code = {
    'guinea bissau': 'gw',
    'guam': 'gu',
    'guatemala': 'gt',
    'greece': 'gr',
    'equatorial guinea': 'gq',
    'guadeloupe': 'gp',
    'guiana': 'gy',
    'french guiana': 'gf',
    'georgia': 'ge',
    'grenada': 'gd',
    'great britain': 'gb',
    'gabon': 'ga',
    'guinea': 'gn',
    'gambia': 'gm',
    'greenland': 'gl',
    'gibraltar': 'gi',
    'ghana': 'gh',
    'tanzania': 'tz',
    'tuvalu': 'tv',
    'taiwan': 'tw',
    'turkey': 'tr',
    'east timor': 'tp',
    'tunisia': 'tn',
    'tonga': 'to',
    'turkmenistan': 'tm',
    'tadjikistan': 'tj',
    'tokelau': 'tk',
    'thailand': 'th',
    'french southern territories': 'tf',
    'togo': 'tg',
    'chad': 'td',
    'dominican republic': 'do',
    'dominica': 'dm',
    'djibouti': 'dj',
    'denmark': 'dk',
    'germany': 'de',
    'algeria': 'dz',
    'vanuatu': 'vu',
    'qatar': 'qa',
    'zambia': 'zm',
    'south africa': 'za',
    'zimbabwe': 'zw',
    'zaire': 'zr',
    'wallis and futuna islands': 'wf',
    'japan': 'jp',
    'jamaica': 'jm',
    'jordan': 'jo',
    'samoa': 'ws',
    'cook islands': 'ck',
    'ivory coast': 'ci',
    'switzerland': 'ch',
    'colombia': 'co',
    'china': 'cn',
    'cameroon': 'cm',
    'chile': 'cl',
    'cocos islands': 'cc',
    'canada': 'ca',
    'congo': 'cg',
    'central african republic': 'cf',
    'the democratic republic of the congo': 'cd',
    'czech republic': 'cz',
    'cyprus': 'cy',
    'christmas island': 'cx',
    'costa rica': 'cr',
    'cape verde': 'cv',
    'cuba': 'cu',
    'puerto rico': 'pr',
    'palau': 'pw',
    'portugal': 'pt',
    'paraguay': 'py',
    'panama': 'pa',
    'french polynesia': 'pf',
    'papua new guinea': 'pg',
    'peru': 'pe',
    'pakistan': 'pk',
    'philippines': 'ph',
    'pitcairn island': 'pn',
    'poland': 'pl',
    'saint pierre and miquelon': 'pm',
    'moldavia': 'md',
    'madagascar': 'mg',
    'morocco': 'ma',
    'monaco': 'mc',
    'myanmar': 'mm',
    'mali': 'ml',
    'macau': 'mo',
    'mongolia': 'mn',
    'marshall islands': 'mh',
    'macedonia': 'mk',
    'mauritius': 'mu',
    'malta': 'mt',
    'malawi': 'mw',
    'maldives': 'mv',
    'martinique': 'mq',
    'northern mariana islands': 'mp',
    'montserrat': 'ms',
    'mauritania': 'mr',
    'malaysia': 'my',
    'mexico': 'mx',
    'mozambique': 'mz',
    'holy see': 'va',
    'venezuela': 've',
    'british virgin islands': 'vg',
    'iraq': 'iq',
    'us virgin islands': 'vi',
    'iceland': 'is',
    'iran': 'ir',
    'italy': 'it',
    'vietnam': 'vn',
    'israel': 'il',
    'british indian ocean territory': 'io',
    'india': 'in',
    'ireland': 'ie',
    'indonesia': 'id',
    'france': 'fr',
    'finland': 'fi',
    'fiji': 'fj',
    'falkland islands': 'fk',
    'micronesia': 'fm',
    'faroe islands': 'fo',
    'swaziland': 'sz',
    'syria': 'sy',
    'suriname': 'sr',
    'el salvador': 'sv',
    'slovak republic': 'sk',
    'slovakia': 'sk',
    'svalbard and jan mayen islands': 'sj',
    'slovenia': 'si',
    'saint helena': 'sh',
    'somalia': 'so',
    'senegal': 'sn',
    'san marino': 'sm',
    'sierra leone': 'sl',
    'seychelles': 'sc',
    'solomon islands': 'sb',
    'saudi arabia': 'sa',
    'singapore': 'sg',
    'sweden': 'se',
    'sudan': 'sd',
    'lebanon': 'lb',
    'saint lucia': 'lc',
    'laos': 'la',
    'sri lanka': 'lk',
    'liechtenstein': 'li',
    'latvia': 'lv',
    'lithuania': 'lt',
    'luxembourg': 'lu',
    'liberia': 'lr',
    'lesotho': 'ls',
    'libya': 'ly',
    'yemen': 'ye',
    'yugoslavia': 'yu',
    'mayotte': 'yt',
    'western sahara': 'eh',
    'estonia': 'ee',
    'egypt': 'eg',
    'ecuador': 'ec',
    'ethiopia': 'et',
    'spain': 'es',
    'eritrea': 'er',
    'russian federation': 'ru',
    'rwanda': 'rw',
    'reunion': 're',
    'romania': 'ro',
    'bangladesh': 'bd',
    'belgium': 'be',
    'burkina faso': 'bf',
    'bulgaria': 'bg',
    'bosnia-herzegovina': 'ba',
    'barbados': 'bb',
    'bermuda': 'bm',
    'brunei darussalam': 'bn',
    'bolivia': 'bo',
    'bahrain': 'bh',
    'burundi': 'bi',
    'benin': 'bj',
    'bhutan': 'bt',
    'bouvet island': 'bv',
    'botswana': 'bw',
    'brazil': 'br',
    'bahamas': 'bs',
    'commonwealth of the bahamas': 'bs',
    'belarus': 'by',
    'belize': 'bz',
    'oman': 'om',
    'croatia': 'hr',
    'haiti': 'ht',
    'hungary': 'hu',
    'hong kong': 'hk',
    'honduras': 'hn',
    'heard and mcdonald islands': 'hm',
    'uruguay': 'uy',
    'uzbekistan': 'uz',
    'united states': 'us',
    'usa': 'us',
    'usa minor outlying islands': 'um',
    'united kingdom': 'uk',
    'uganda': 'ug',
    'ukraine': 'ua',
    'united arab emirates': 'ae',
    'principality of andorra': 'ad',
    'antigua': 'ag',
    'afghanistan': 'af',
    'anguilla': 'ai',
    'armenia': 'am',
    'albania': 'al',
    'angola': 'ao',
    'netherlands antilles': 'an',
    'antarctica': 'aq',
    'american samoa': 'as',
    'argentina': 'ar',
    'australia': 'au',
    'austria': 'at',
    'aruba': 'aw',
    'azerbaidjan': 'az',
    'nicaragua': 'ni',
    'netherlands': 'nl',
    'the netherlands': 'nl',
    'norway': 'no',
    'namibia': 'na',
    'new caledonia': 'nc',
    'niger': 'ne',
    'norfolk island': 'nf',
    'nigeria': 'ng',
    'new zealand': 'nz',
    'nepal': 'np',
    'nauru': 'nr',
    'neutral zone': 'nt',
    'niue': 'nu',
    'kyrgyzstan': 'kg',
    'kenya': 'ke',
    'kiribati': 'ki',
    'cambodia, kingdom of': 'kh',
    'comoros': 'km',
    'south korea': 'kr',
    'north korea': 'kp',
    'kuwait': 'kw',
    'kazakhstan': 'kz',
    'cayman islands': 'ky',
}

state_name_to_code = {
    'alabama': 'al',
    'alaska': 'ak',
    'arizona': 'az',
    'arkansas': 'ar',
    'california': 'ca',
    'colorado': 'co',
    'connecticut': 'ct',
    'delaware': 'de',
    'district of columbia': 'dc',
    'florida': 'fl',
    'georgia': 'ga',
    'hawaii': 'hi',
    'idaho': 'id',
    'illinois': 'il',
    'indiana': 'in',
    'iowa': 'ia',
    'kansas': 'ks',
    'kentucky': 'ky',
    'louisiana': 'la',
    'maine': 'me',
    'maryland': 'md',
    'massachusetts': 'ma',
    'michigan': 'mi',
    'minnesota': 'mn',
    'mississippi': 'ms',
    'missouri': 'mo',
    'montana': 'mt',
    'nebraska': 'ne',
    'nevada': 'nv',
    'new hampshire': 'nh',
    'new jersey': 'nj',
    'new mexico': 'nm',
    'new york': 'ny',
    'north carolina': 'nc',
    'north dakota': 'nd',
    'ohio': 'oh',
    'oklahoma': 'ok',
    'oregon': 'or',
    'pennsylvania': 'pa',
    'rhode island': 'ri',
    'south carolina': 'sc',
    'south dakota': 'sd',
    'tennessee': 'tn',
    'texas': 'tx',
    'utah': 'ut',
    'vermont': 'vt',
    'virginia': 'va',
    'washington': 'wa',
    'west virginia': 'wv',
    'wisconsin': 'wi',
    'wyoming': 'wy'
}
