job_titles = {
    'A': [
        'Account Executive',
        'Application Developer',
        'Account Manager',
        'Architect',
        'Account Representative',
        'Art Director',
        'Accountant',
        'Assembler',
        'Accounting Assistant',
        'Assistant',
        'Accounting Clerk',
        'Assistant Controller',
        'Accounting Manager',
        'Assistant Editor',
        'Accounts Payable Clerk',
        'Assistant Manager',
        'Accounts Payable Specialist',
        'Assistant Project Manager',
        'Accounts Receivable Clerk',
        'Assistant Property Manager',
        'Administrative Assistant',
        'Assistant Store Manager',
        'Administrative Coordinator',
        'Assistant Teacher',
        'Administrative Specialist',
        'Attorney',
        'Analyst',
        'Autocad Drafter',
        'Analytical Chemist',
        'Automotive Technician'
    ],
    'B': [
        'Baker',
        'Broadband Technician',
        'Bank Teller',
        'Budget Analyst',
        'Banker',
        'Bus Driver',
        'Banquet Manager',
        'Business Analyst',
        'Bartender',
        'Business Developer',
        'Benefits Administrator',
        'Business Development Associate',
        'Benefits Manager',
        'Business Development Manager',
        'Benefits Specialist',
        'Business Development Specialist',
        'Billing Clerk',
        'Business Manager',
        'Billing Specialist',
        'Business Objects Developer',
        'Bookkeeper',
        'Business Office Manager',
        'Branch Customer Service Representative',
        'Business Process Analyst',
        'Branch Manager',
        'Business Systems Analyst',
        'Branch Office Administrator',
        'Buyer',
        'Brand Manager',
        'Buyer Planner'
    ],
    'C': [
        'Carpenter',
        'Construction Manager',
        'Case Manager',
        'Construction Superintendent',
        'Cashier',
        'Construction Worker',
        'Certified Nursing Assistant',
        'Contract Specialist',
        'Chemist',
        'Controller',
        'Chief Financial Officer',
        'Cook',
        'Civil Engineer',
        'Copywriter',
        'Clerk',
        'Counselor',
        'Clinical Pharmacist',
        'Credit Analyst',
        'Cna',
        'Criminal Investigator',
        'Cnc Machinist',
        'Custodian',
        'Commercial Sales Manager',
        'Customer Service Advisor',
        'Communications Specialist',
        'Customer Service Associate',
        'Community Volunteer',
        'Customer Service Manager',
        'Computer Scientist',
        'Customer Service Representative'
     ],
    'D': [
        'Data Analyst',
        'Director Of Communication',
        'Data Entry Clerk',
        'Director Of Development',
        'Data Entry Operator',
        'Director Of Finance',
        'Database Administrator',
        'Director Of Human Resources',
        'Delivery Driver',
        'Director Of Marketing',
        'Dental Assistant',
        'Director Of Nursing',
        'Dental Hygienist',
        'Director Of Operations',
        'Design Engineer',
        'Director Of Sales',
        'Designer',
        'Dishwasher',
        'Desktop Support',
        'Dispatcher',
        'Desktop Support Technician',
        'District Manager',
        'Development Associate',
        'District Sales Manager',
        'Diesel Mechanic',
        'Drafter',
        'Director',
        'Driver',
        'Director Of Business Development',
        'Driver Merchandiser'
    ],
    'E': [
        'Editor',
        'Environmental Engineer',
        'Editorial Assistant',
        'Environmental Scientist',
        'Electrical Designer',
        'Equipment Operator',
        'Electrical Engineer',
        'Escrow Assistant',
        'Electrician',
        'Esthetician',
        'Electronic Assembler',
        'Estimator',
        'Electronics Engineer',
        'Event Manager',
        'Electronics Technician',
        'Event Planner',
        'Embedded Software Engineer',
        'Executive Administrative Assistant',
        'Emergency Road Service Counselor',
        'Executive Assistant',
        'Engineer',
        'Executive Chef',
        'Engineering Manager',
        'Executive Director',
        'Engineering Technician',
        'Executive Personal Assistant',
        'Enrollment Counselor',
        'Executive Recruiter',
        'Enterprise Architect',
        'Executive Secretary'
    ],
    'F': [
        'Facilities Coordinator',
        'Financial Associate',
        'Facilities Manager',
        'Financial Reporting Manager',
        'Federal Government Worker',
        'Firefighter',
        'Field Engineer',
        'Flight Attendant',
        'Field Investigator',
        'Floral Designer',
        'Field Representative',
        'Food Service Worker',
        'Field Sales Representative',
        'Footwear Associate',
        'Field Service Engineer',
        'Forklift Operator',
        'Field Service Representative',
        'Fraud Investigator',
        'Field Service Technician',
        'Freight Team Associate',
        'Field Technician',
        'Front Desk Clerk',
        'File Clerk',
        'Front Desk Coordinator',
        'Finance Manager',
        'Front Desk Receptionist',
        'Financial Advisor',
        'Front Office Manager',
        'Financial Analyst',
        'Full Charge Bookkeeper'
    ], 
    'G': [
        'Game Manager',
        'Gis Developer',
        'Garden Sales Associate',
        'Gis Specialist',
        'General Clerk',
        'Gis Technician',
        'General Counsel',
        'Grant Writer',
        'General Engineer',
        'Graphic Artist',
        'General Ledger Accountant',
        'Graphic Web Designer',
        'General Maintenance Technician',
        'Graphics Designer',
        'General Manager',
        'Graphics Designer Production Artist',
        'General Office Assistant',
        'Greeter',
        'General Office Clerk',
        'Grill Cook',
        'General Service Technician',
        'Grooming Salon Manager',
        'Geographer',
        'Groundskeeper',
        'Geologist',
        'Guest Service Agent',
        'Geotechnical Engineer',
        'Guidance Counselor',
        'Gis Analyst'
    ],
    'H': [
        'Hair Stylist',
        'Help Desk Technician',
        'Handyman',
        'Home Health Aide',
        'Hardware Design Engineer',
        'Household Driver',
        'Hardware Engineer',
        'Housekeeper',
        'Hardware Engineering Manager',
        'Housekeeping Supervisor',
        'Hardware Technician',
        'Hr Administrative Assistant',
        'Head Cashier',
        'Hr Administrator',
        'Head Teller',
        'Hr Consultant',
        'Health Educator',
        'Hr Coordinator',
        'Health Systems Specialist',
        'Hr Generalist',
        'Health Unit Coordinator',
        'Hr Manager',
        'Heavy Equipment Operator',
        'Hr Recruiter',
        'Help Desk Analyst',
        'Hr Representative',
        'Help Desk Specialist',
        'Hr Specialist',
        'Help Desk Technical Support',
        'Hvac Technician'
    ],
    'I': [
        'Illustrator',
        'Interior Design Assistant',
        'In Store Banker',
        'Interior Designer',
        'Industrial Designer',
        'Internal Auditor',
        'Industrial Electrician',
        'International Police Officer',
        'Industrial Engineer',
        'Inventory Analyst',
        'Informatica Developer',
        'Inventory Clerk',
        'Inside Sales',
        'Inventory Management Associate',
        'Inside Sales Representative',
        'Inventory Specialist',
        'Inspector',
        'Investigator',
        'Installer',
        'Investment Analyst',
        'Instructional Designer',
        'It Auditor',
        'Instructor',
        'It Director',
        'Insurance Agent',
        'It Manager',
        'Insurance Sales Representative',
        'It Project Manager',
        'Intelligence Analyst',
        'It Specialist'
    ],
    'J': [
        'J2ee Architect',
        'Java Team Lead',
        'J2ee Developer',
        'Java Web Developer',
        'J2ee Software Engineer',
        'Java Websphere Developer',
        'J2me Consultant',
        'Jeweler',
        'Janitor',
        'Job Captain',
        'Janitorial Supervisor',
        'Job Coach',
        'Java',
        'Job Developer',
        'Java Application Developer',
        'Journalist',
        'Java Architect',
        'Journeyman',
        'Java Developer',
        'Journeyman Electrician',
        'Java J2ee Developer',
        'Journeyman Lineman',
        'Java Programmer',
        'Journeyman Plumber',
        'Java Software Developer',
        'Judge Advocate',
        'Java Software Engineer',
        'Juvenile Detention Officer',
        'Java Swing Developer',
        'Juvenile Probation Officer'
    ], 
    'K': [
        'K12 Account Manager',
        'Kitchen Manager',
        'Kennel Assistant',
        'Kitchen Mechanic',
        'Kennel Attendant',
        'Kitchen Staff',
        'Kennel Technician',
        'Kitchen Steward',
        'Key Account Manager',
        'Kitchen Supervisor',
        'Key Holder',
        'Kitchen Worker',
        'Kidney Transpart Coordinator',
        'Knowledge Engineer',
        'Kids Activity Assistant',
        'Knowledge Management Specialist',
        'Kindergarten Teacher',
        'Knowledge Manager',
        'Kinesiotherapist',
        'Korean - Test Associate - Gaming',
        'Kitchen Assistant',
        'Korean Language Instructor',
        'Kitchen Bath Department Supervisor',
        'Kronos Implementation',
        'Kitchen Bath Sales Associate',
        'Kronos Programmer',
        'Kitchen Designer',
        'Kronos Systems Administrator',
        'Kitchen Helper',
        'Kronos Workforce Timekeeper Engineer'
    ],
    'L': [
        'Lab Assistant',
        'Licensed Vocational Nurse lvn',
        'Lab Technician',
        'Lifeguard',
        'Laborer',
        'Line Cook',
        'Land Surveyor',
        'Litigation Attorney',
        'Landscape Architect',
        'Litigation Paralegal',
        'Lead Asset Protection Associate',
        'Loan Consultant',
        'Lease Administrator',
        'Loan Officer',
        'Leasing Agent',
        'Loan Processor',
        'Leasing Consultant',
        'Logistics Analyst',
        'Legal Administrative Assistant',
        'Logistics Coordinator',
        'Legal Assistant',
        'Logistics Manager',
        'Legal Secretary',
        'Loss Prevention Investigator',
        'Librarian',
        'Loss Prevention Manager',
        'Library Assistant',
        'Lot Attendent',
        'Licensed Practical Nurse lpn',
        'Lotus Notes Developer'
    ],
    'M': [
        'Machine Operator',
        'Marketing Manager',
        'Machinist',
        'Marketing Specialist',
        'Mail Clerk',
        'Massage Therapist',
        'Maintenance Manager',
        'Material Handler',
        'Maintenance Mechanic',
        'Mechanic',
        'Maintenance Supervisor',
        'Mechanical Design Engineer',
        'Maintenance Technician',
        'Mechanical Engineer',
        'Maintenance Worker',
        'Medical Assistant',
        'Manager',
        'Medical Receptionist',
        'Manufacturing Engineer',
        'Medical Records Clerk',
        'Market Research Analyst',
        'Medical Technologist',
        'Marketing Assistant',
        'Medical Worker',
        'Marketing Associate',
        'Merchandiser',
        'Marketing Coordinator',
        'Mortgage Loan Officer'
    ],
    'N': [
        'Nanny',
        'News Reporter',
        'National Account Manager',
        'Night Auditor',
        'National Sales Manager',
        'Night Manager',
        'Nationwide Truck Driver',
        'Noc Technician',
        'Neonatal Nurse Practitioner',
        'Nuclear Medicine Technologist',
        'Net Developer',
        'Nurse',
        'Network Administrator',
        'Nurse Assistant',
        'Network Analyst',
        'Nurse Lvn',
        'Network Engineer',
        'Nurse Manager',
        'Network Manager',
        'Nurse Practitioner',
        'Network Security Engineer',
        'Nurse Recruiter',
        'Network Specialist',
        'Nurse Rn',
        'Network System Administrator',
        'Nursing Assistant',
        'Network Technician',
        'Nursing Home Administrator',
        'News Producer',
        'Nutritionist'
    ], 
    'O': [
        'Occupational Therapist',
        'Operations Research Analyst',
        'Occupational Therapy Assistant',
        'Operations Specialist',
        'Office Administrator',
        'Operations Supervisor',
        'Office Assistant',
        'Operator',
        'Office Automation Clerk',
        'Optical Engineer',
        'Office Clerk',
        'Optician',
        'Office Coordinator',
        'Oracle Database Administrator',
        'Office Manager',
        'Oracle Developer',
        'Office Manager Administrative Assistant',
        'Oracle Pl Sql Developer',
        'Office Manager Bookkeeper',
        'Order Builder',
        'Online Marketing Manager',
        'Otr Drivers',
        'Operations Analyst',
        'Outreach Coordinator',
        'Operations Assistant',
        'Outside Sales Preset Appointment',
        'Operations Coordinator',
        'Outside Sales Representative',
        'Operations Manager',
        'Owner Operators / Fleet Owners'
    ],
    'P': [
        'Painter',
        'Product Marketing Manager',
        'Paralegal',
        'Production Assistant',
        'Payroll Specialist',
        'Production Manager',
        'Personal Assistant',
        'Production Supervisor',
        'Pharmaceutical Sales Representative',
        'Production Worker',
        'Pharmacist',
        'Program Coordinator',
        'Pharmacy Technician',
        'Program Manager',
        'Phlebotomist',
        'Programmer Analyst',
        'Photographer',
        'Project Coordinator',
        'Physical Therapist',
        'Project Engineer',
        'Physician Assistant',
        'Project Manager',
        'Plant Manager',
        'Property Manager',
        'Police Officer',
        'Public Relations Manager',
        'Process Engineer',
        'Purchasing Agent',
        'Product Manager',
        'Purchasing Manager'    
    ],
    'Q': [
        'Qa Analyst',
        'Quality Auditor',
        'Qa Associate',
        'Quality Control',
        'Qa Auditor',
        'Quality Control Chemist',
        'Qa Engineer',
        'Quality Control Inspector',
        'Qa Inspector',
        'Quality Control Lab Technician',
        'Qa Lead',
        'Quality Control Manager',
        'Qa Specialist',
        'Quality Control Specialist',
        'Qa Supervisor',
        'Quality Control Supervisor',
        'Qa Technician',
        'Quality Control Technician',
        'Qa Tester',
        'Quality Coordinator',
        'Quality Analyst',
        'Quality Engineer',
        'Quality Assurance Analyst',
        'Quality Maintenance Technician',
        'Quality Assurance Engineer',
        'Quality Manager',
        'Quality Assurance Manager',
        'Quantitative Analyst',
        'Quality Assurance Specialist',
        'Quantitative Research Analyst'
    ],
    'R': [
        'Real Estate Appraiser',
        'Research Assistant',
        'Receiving Associate',
        'Research Associate',
        'Receiving Merchandise Pick Up Associate',
        'Research Scientist',
        'Receptionist',
        'Respiratory Therapist',
        'Receptionist Administrative Assistant',
        'Restaurant Bartender',
        'Receptionist Switchboard',
        'Restaurant Manager',
        'Recruiter',
        'Restaurant Worker',
        'Recruiting Coordinator',
        'Retail Customer Support Representative',
        'Recruiting Manager',
        'Retail Merchandiser',
        'Red Cross',
        'Retail Sales Associate',
        'Regional Manager',
        'Retail Sales Representative',
        'Regional Sales Manager',
        'Retail Store Manager',
        'Relationship Manager',
        'Rn',
        'Representative Retail Sales',
        'Route Driver',
        'Research Analyst',
        'Route Sales Representative'
    ],
    'S': [
        'Safety Manager',
        'Senior Accountant',
        'Sales',
        'Service Manager',
        'Sales Assistant',
        'Service Technician',
        'Sales Associate',
        'Shipping Clerk',
        'Sales Consultant',
        'Social Worker',
        'Sales Coordinator',
        'Software Engineer',
        'Sales Engineer',
        'Sous Chef',
        'Sales Executive',
        'Special Events Coordinator',
        'Sales Manager',
        'Staff Accountant',
        'Sales Representative',
        'Store Manager',
        'Sales Specialist',
        'Superintendent',
        'Scientist',
        'Supervisor',
        'Secretary',
        'System Administrator',
        'Security Guard',
        'Systems Analyst',
        'Security Officer',
        'Systems Engineer'
    ],
    'T': [
        'Tax Accountant',
        'Territory Manager',
        'Tax Manager',
        'Territory Sales Manager',
        'Teacher',
        'Test Engineer',
        'Technical Project Manager',
        'Test Technician',
        'Technical Recruiter',
        'Tester',
        'Technical Sales Representative',
        'Trader',
        'Technical Support Engineer',
        'Trainer',
        'Technical Support Specialist',
        'Training Coordinator',
        'Technical Trainer',
        'Training Manager',
        'Technical Writer',
        'Training Specialist',
        'Technician',
        'Transportation Manager',
        'Telecommunications Specialist',
        'Transportation Security Officer',
        'Telecommunications Technician',
        'Travel Agent',
        'Telemarketer',
        'Treasury Analyst',
        'Teller',
        'Truck Driver'
    ],
    'U': [
        'U-haul Center Manager',
        'Unit Coordinator',
        'Ui Designer',
        'Unit Manager',
        'Ultrasonographer',
        'Unit Secretary',
        'Ultrasound Technician',
        'Universal Banker',
        'Ultrasound Technologist',
        'Universal Service Representative',
        'Unarmed Security Guard',
        'Unix Administrator',
        'Underwriter',
        'Unix Engineer',
        'Underwriter Trainee',
        'Unix System Administrator',
        'Underwriting Assistant',
        'Upholsterer',
        'Uniform Sales Associate',
        'Urban Planner',
        'Uniform Sales Representative',
        'Usability Engineer',
        'Unigraphics Designer',
        'Usar Unit Administrator',
        'Unit Assistant',
        'User Interface Designer',
        'Unit Clerk',
        'Utility Worker',
        'Unit Controller',
        'Utilization Review Nurse'
    ],
    'V': [
        'Valet Attendant',
        'Vocational Rehabilitation Specialist',
        'Validation Engineer',
        'Volunteer Coordinator',
        'Van Driver',
        'Volunteer Recruiter',
        'Vascular Technologist',
        'VP',
        'Vb Net Developer',
        'VP Director Of Finance',
        'Veterinarian',
        'VP Of Business Development',
        'Veterinary Assistant',
        'VP Of Development',
        'Veterinary Receptionist',
        'VP Of Engineering',
        'Veterinary Technician',
        'VP Of Finance',
        'Video Editor',
        'VP Of Human Resources',
        'Virtual Assistant',
        'VP Of Information Technology',
        'Visual Basic Developer',
        'VP Of Marketing',
        'Visual Information Specialist',
        'VP Of Operations',
        'Visual Merchandiser',
        'VP Of Sales',
        'Vocational Rehabilitation Counselor',
        'VP Of Sales & Marketing'
    ],
    'W': [
        'Wait Staff',
        'Web Programmer',
        'Warehouse Assistant',
        'Web Project Manager',
        'Warehouse Associate',
        'Webmaster',
        'Warehouse Clerk',
        'Websphere Administrator',
        'Warehouse Coordinator',
        'Welder',
        'Warehouse Driver',
        'Welder Fabricator',
        'Warehouse Lead',
        'Wff Usc Credit Manager',
        'Warehouse Manager',
        'Wholesale Account Executive',
        'Warehouse Operator',
        'Wildlife Biologist',
        'Warehouse Specialist',
        'Windows System Administrator',
        'Warehouse Supervisor',
        'Wireless Consultant',
        'Warehouse Worker',
        'Word Processor',
        'Web Designer',
        'Work Sales Representative',
        'Web Developer',
        'Writer',
        'Web Producer',
        'Writer Editor'
    ], 
    'X': [
        'X-band Radar Electrical Engineer',
        'Xforms & Xml Development Specialist',
        'X-ray File Clerk',
        'Xgen Developer',
        'X-ray Floater',
        'Xml Developer',
        'X-ray Prepper',
        'Xml Extraction Expert',
        'X-ray Supervisor',
        'Xml Specialist',
        'X-ray Tech',
        'Xml-vb Developer',
        'X-ray Technician, Radiology',
        'Xml-xsl Developer',
        'X-ray Technician/basic Machine Operator',
        'Xpress Integration Specialist',
        'X-ray Technologist',
        'Xps Sales Agent',
        'Xcellenet Developer',
        'Xsd Developer',
        'Xcelsius Consultant',
        'Xseries Linux Technical Consultant',
        'Xerox Operator',
        'Xseries/linux Specialist',
        'Xerox Sales Agent Representative',
        'Xsl Developer',
        'Xerox Sales Representative',
        'Xslt Developer'
    ],
    'Y': [
        'Youth Activities Associate',
        'Youth Activities Staff',
        'Youth Basketball Instructor',
        'Youth Care Specialist',
        'Youth Care Worker',
        'Youth Coordinator',
        'Youth Counselor',
        'Youth Department Sales Manager',
        'Youth Development Manager',
        'Youth Development Specialist',
        'Youth Leader',
        'Youth Program Coordinator',
        'Youth Program Director',
        'Youth Specialist',
        'Youth Worker',
        'Youth Advocate'
    ],
    'Z':[
        'Zebrafish Core Facility Junior Scientist',
        'Zebrafish Core Facility Manager'
    ],
 }
