job_categories = [
    'Accounting & Finance',
    'Healthcare',
    'Non-Profit & Volunteering',
    'Administrative',
    'Computer & Internet',
    'Pharmaceutical & Bio-tech',
    'Arts & Entertainment & Publishing',
    'Hospitality & Travel',
    'Real Estate',
    'Banking & Loans',
    'Human Resources',
    'Restaurant & Food Service',
    'Construction & Facilities',
    'Insurance',
    'Retail',
    'Customer Service',
    'Law Enforcement & Security',
    'Sales',
    'Education & Training',
    'Legal',
    'Telecommunications',
    'Engineering & Architecture',
    'Manufacturing & Mechanical',
    'Transportation & Logistics',
    'Government & Military',
    'Marketing & Advertising & PR',
    'Upper Management & Consulting'
]

job_category_titles = {
    'Accounting & Finance': [
        'Accountant',
        'Director Of Finance',
        'Office Manager Bookkeeper',
        'Accounting Assistant',
        'Finance Manager',
        'Quantitative Analyst',
        'Accounting Clerk',
        'Financial Advisor',
        'Quantitative Research Analyst',
        'Accounting Manager',
        'Financial Analyst',
        'Senior Accountant',
        'Assistant Controller',
        'Financial Associate',
        'Tax Accountant',
        'Billing Specialist',
        'Financial Reporting Manager',
        'Tax Manager',
        'Bookkeeper',
        'Full Charge Bookkeeper',
        'Treasury Analyst',
        'Budget Analyst',
        'General Ledger Accountant',
        'VP Director of Finance',
        'CNA',
        'Internal Auditor',
        'VP of Finance',
        'Controller',
        'Night Auditor',
        'WFF USC Credit Manager'
    ],
    'Healthcare': [
        'Case Manager',
        'Medical Worker',
        'Phlebotomist',
        'Dental Assistant',
        'Nuclear Medicine Technologist',
        'Physical Therapist',
        'Dental Hygienist',
        'Nurse',
        'Physician Assistant',
        'Director of Nursing',
        'Nurse Assistant',
        'Respiratory Therapist',
        'Health Unit Coordinator',
        'Nurse LVN',
        'Social Worker',
        'Home Health Aide',
        'Nurse Practitioner',
        'Unit Clerk',
        'Massage Therapist',
        'Nurse RN',
        'Unit Secretary',
        'Medical Assistant',
        'Nursing Assistant',
        'Veterinary Receptionist',
        'Medical Receptionist',
        'Nutritionist',
        'Veterinary Technician',
        'Medical Technologist',
        'Occupational Therapist',
        'Vocational Rehabilitation Counselor'
    ],
    'Non-Profit & Volunteering': [
        'Community Volunteer',
        'Youth Care Specialist',
        'Youth Leader',
        'Red Cross',
        'Youth Care Worker',
        'Youth Program Coordinator',
        'Special Events Coordinator',
        'Youth Coordinator',
        'Youth Program Director',
        'Volunteer Coordinator',
        'Youth Counselor',
        'Youth Specialist',
        'Volunteer Recruiter',
        'Youth Development Manager',
        'Youth Worker',
        'Youth Advocate',
        'Youth Development Specialist'
    ],
    'Administrative': [
        'Accounts Payable Clerk',
        'Executive Assistant',
        'Program Coordinator',
        'Accounts Receivable Clerk',
        'Executive Director',
        'Program Manager',
        'Administrative Assistant',
        'File Clerk',
        'Project Coordinator',
        'Assistant Manager',
        'Medical Records Clerk',
        'Project Manager',
        'Branch Manager',
        'Office Assistant',
        'Purchasing Agent',
        'Clerk',
        'Office Clerk',
        'Purchasing Manager',
        'Data Entry Operator',
        'Office Manager',
        'Receptionist',
        'Director of Operations',
        'Operations Manager',
        'Receptionist Administrative Assistant',
        'District Manager',
        'Personal Assistant',
        'Secretary',
        'Executive Administrative Assistant',
        'Product Manager',
        'Territory Manager'
    ],
    'Computer & Internet': [
        'Application Developer',
        'IT Specialist',
        'Software Engineer',
        'Business Objects Developer',
        'Informatica Developer',
        'System Administrator',
        'Business Systems Analyst',
        'Java Developer',
        'Systems Analyst',
        'Data Analyst',
        'NET Developer',
        'Systems Engineer',
        'Database Administrator',
        'Network Administrator',
        'Technical Support Engineer',
        'Director Of Development',
        'Network Engineer',
        'Technical Support Specialist',
        'Embedded Software Engineer',
        'Network Technician',
        'Unix System Administrator',
        'IT Director',
        'Oracle Database Administrator',
        'Web Designer',
        'IT Manager',
        'Oracle Developer',
        'Web Developer',
        'IT Project Manager',
        'Programmer Analyst',
        'Webmaster'
    ],
    'Pharmaceutical & Bio-tech': [
        'Analytical Chemist',
        'Lab Technician',
        'Pharmacist',
        'Lab Assistant',
        'Pharmaceutical Sales Representative',
        'Pharmacy Technician'
    ],
    'Arts & Entertainment & Publishing': [
        'Art Director',
        'Graphics Designer',
        'Unigraphics Designer',
        'Assistant Editor',
        'Graphics Designer Production Artist',
        'User Interface Designer',
        'Designer',
        'Illustrator',
        'Video Editor',
        'Editor',
        'Journalist',
        'Writer',
        'Editorial Assistant',
        'News Producer',
        'Writer Editor',
        'Graphic Artist',
        'News Reporter',
        'Zoo Keeper',
        'Graphic Web Designer',
        'Photographer'
    ],
    'Hospitality & Travel': [
        'Banquet Manager',
        'Greeter',
        'Kennel Attendant',
        'Event Manager',
        'Guest Service Agent',
        'Kennel Technician',
        'Event Planner',
        'Housekeeper',
        'Travel Agent',
        'Floral Designer',
        'Kennel Assistant'
    ],
    'Real Estate': [
        'Assistant Property Manager',
        'Leasing Agent',
        'Real Estate Appraiser',
        'Land Surveyor',
        'Leasing Consultant',
        'Lease Administrator',
        'Property Manager'
    ],
    'Banking & Loans': [
        'Analyst',
        'Investment Analyst',
        'Underwriter',
        'Bank Teller',
        'Loan Consultant',
        'Underwriter Trainee',
        'Banker',
        'Loan Officer',
        'Underwriting Assistant',
        'Credit Analyst',
        'Loan Processor',
        'Universal Banker',
        'Escrow Assistant',
        'Mortgage Loan Officer',
        'In Store Banker',
        'Teller'
     ],
    'Human Resources': [
        'Director Of Human Resources',
        'HR Manager',
        'Recruiting Coordinator',
        'Executive Recruiter',
        'HR Recruiter',
        'Recruiting Manager',
        'HR Administrator',
        'HR Representative',
        'Technical Recruiter',
        'HR Consultant',
        'HR Specialist',
        'VP of Human Resources',
        'HR Coordinator',
        'Job Coach',
        'HR Generalist',
        'Recruiter',
        'Director of Benefits',
        'Wellness Coordinator'
     ],
    'Restaurant & Food Service': [
        'Baker',
        'Kitchen Bath Department Supervisor',
        'Line Cook',
        'Bartender',
        'Kitchen Designer',
        'Restaurant Bartender',
        'Cook',
        'Kitchen Helper',
        'Restaurant Manager',
        'Dishwasher',
        'Kitchen Manager',
        'Restaurant Worker',
        'Executive Chef',
        'Kitchen Staff',
        'Sous Chef',
        'Food Service Worker',
        'Kitchen Steward',
        'Wait Staff',
        'Grill Cook',
        'Kitchen Supervisor',
        'Kitchen Assistant',
        'Kitchen Worker'
    ],
    'Construction & Facilities': [
        'Carpenter',
        'Groundskeeper',
        'Laborer',
        'Construction Manager',
        'HVAC Technician',
        'Maintenance Manager',
        'Construction Superintendent',
        'Heavy Equipment Operator',
        'Maintenance Mechanic',
        'Construction Worker',
        'Industrial Designer',
        'Maintenance Supervisor',
        'Custodian',
        'Industrial Electrician',
        'Maintenance Technician',
        'Electrician',
        'Installer',
        'Maintenance Worker',
        'Equipment Operator',
        'Interior Designer',
        'Painter',
        'Estimator',
        'Janitor',
        'Plant Manager',
        'Facilities Manager',
        'Journeyman Electrician',
        'Welder',
        'General Maintenance Technician',
        'Journeyman Lineman',
        'Welder Fabricator'
    ],
    'Insurance': [
        'Benefits Administrator',
        'Fraud Investigator',
        'Investigator',
        'Benefits Manager',
        'Inspector',
        'Lead Asset Protection Associate',
        'Benefits Specialist',
        'Insurance Agent',
        'Field Investigator',
        'Insurance Sales Representative'
    ],
    'Retail': [
        'Assistant Store Manager',
        'Hair Stylist',
        'Retail Sales Representative',
        'Buyer',
        'Head Cashier',
        'Retail Store Manager',
        'Buyer Planner',
        'Jeweler',
        'Sales Assistant',
        'Cashier',
        'Key Holder',
        'Store Manager',
        'Esthetician',
        'Kitchen Bath Sales Associate',
        'Visual Merchandiser',
        'Footwear Associate',
        'Night Manager',
        'Youth Department Sales Manager',
        'Garden Sales Associate',
        'Representative Retail Sales',
        'Grooming Salon Manager',
        'Retail Sales Associate'
    ],
    'Customer Service': [
        'Branch Customer Service Representative',
        'Field Service Representative',
        'Lot Attendent',
        'Customer Service Advisor',
        'Field Service Technician',
        'Relationship Manager',
        'Customer Service Associate',
        'Field Technician',
        'Retail Customer Support Representative',
        'Customer Service Manager',
        'Flight Attendant',
        'Sales Engineer',
        'Customer Service Representative',
        'Game Manager',
        'Service Manager',
        'Desktop Support',
        'General Service Technician',
        'Service Technician',
        'Desktop Support Technician',
        'Help Desk Analyst',
        'Universal Service Representative',
        'Emergency Road Service Counselor',
        'Help Desk Specialist',
        'Valet Attendant',
        'Field Engineer',
        'Help Desk Technical Support',
        'Field Service Engineer',
        'Help Desk Technician'
    ],
    'Law Enforcement & Security': [
        'Criminal Investigator',
        'Loss Prevention Investigator',
        'Security Officer',
        'International Police Officer',
        'Loss Prevention Manager',
        'Transportation Security Officer',
        'Juvenile Detention Officer',
        'Police Officer',
        'Unarmed Security Guard',
        'Juvenile Probation Officer',
        'Security Guard'
    ],
    'Sales': [
        'Account Executive',
        'Key Account Manager',
        'Sales Coordinator',
        'Account Manager',
        'Merchandiser',
        'Sales Executive',
        'Account Representative',
        'National Account Manager',
        'Sales Manager',
        'Business Development Manager',
        'National Sales Manager',
        'Sales Representative',
        'Business Development Specialist',
        'Outside Sales Representative',
        'Sales Specialist',
        'Director Of Business Development',
        'Regional Sales Manager',
        'Telemarketer',
        'Director Of Sales',
        'Retail Merchandiser',
        'Territory Sales Manager',
        'District Sales Manager',
        'Route Sales Representative',
        'Trader',
        'Field Representative',
        'Sales Associate',
        'VP of Sales',
        'Inside Sales Representative',
        'Sales Consultant',
        'Work Sales Representative'
    ],
    'Education & Training': [
        'Assistant Teacher',
        'Kids Activity Assistant',
        'Trainer',
        'Counselor',
        'Kindergarten Teacher',
        'Training Coordinator',
        'Enrollment Counselor',
        'Korean Language Instructor',
        'Training Manager',
        'Guidance Counselor',
        'Nanny',
        'Training Specialist',
        'Health Educator',
        'Teacher',
        'Yoga Instructor',
        'Instructional Designer',
        'Technical Trainer',
        'Instructor',
        'Professor',
        'Associate Professor',
        'Technical Writer'
    ],
    'Legal': [
        'Attorney',
        'Legal Administrative Assistant',
        'Litigation Attorney',
        'General Counsel',
        'Legal Assistant',
        'Litigation Paralegal',
        'Judge Advocate',
        'Legal Secretary',
        'Paralegal'
    ],
    'Telecommunications': [
        'Broadband Technician',
        'Telecommunications Specialist',
        'Wireless Consultant',
        'Communications Specialist',
        'Telecommunications Technician',
        'ZURB Operator'
    ],
    'Engineering & Architecture': [
        'Architect',
        'GIS Analyst',
        'Mechanical Design Engineer',
        'Civil Engineer',
        'GIS Specialist',
        'Mechanical Engineer',
        'Design Engineer',
        'GIS Technician',
        'Operations Research Analyst',
        'Electrical Designer',
        'General Engineer',
        'Optical Engineer',
        'Electrical Engineer',
        'Geographer',
        'Process Engineer',
        'Electronics Engineer',
        'Geologist',
        'Project Engineer',
        'Engineer',
        'Geotechnical Engineer',
        'Scientist',
        'Engineering Manager',
        'Hardware Design Engineer',
        'Test Engineer',
        'Engineering Technician',
        'Hardware Engineer',
        'Ultrasound Technician',
        'Environmental Engineer',
        'Industrial Engineer',
        'VP Of Engineering'
    ],
    'Manufacturing & Mechanical': [
        'Assembler',
        'Manufacturing Engineer',
        'QA Tester',
        'Autocad Drafter',
        'Material Handler',
        'Quality Control Inspector',
        'Automotive Technician',
        'Operator',
        'Quality Engineer',
        'CNC Machinist',
        'Production Assistant',
        'Research Analyst',
        'Chemist',
        'Production Manager',
        'Research Assistant',
        'Drafter',
        'Production Supervisor',
        'Research Associate',
        'Electronic Assembler',
        'Production Worker',
        'Research Scientist',
        'Electronics Technician',
        'QA Analyst',
        'Safety Manager',
        'Machine Operator',
        'QA Engineer',
        'Technician',
        'Machinist',
        'QA Specialist',
        'Test Technician'
    ],
    'Transportation & Logistics': [
        'Bus Driver',
        'Logistics Coordinator',
        'Van Driver',
        'Delivery Driver',
        'Logistics Manager',
        'Warehouse Assistant',
        'Diesel Mechanic',
        'Nationwide Truck Driver',
        'Warehouse Associate',
        'Dispatcher',
        'Order Builder',
        'Warehouse Clerk',
        'Driver',
        'Receiving Associate',
        'Warehouse Driver',
        'Driver Merchandiser',
        'Receiving Merchandise Pick Up Associate',
        'Warehouse Lead',
        'Forklift Operator',
        'Route Driver',
        'Warehouse Manager',
        'Freight Team Associate',
        'Shipping Clerk',
        'Warehouse Specialist',
        'Household Driver',
        'Transportation Manager',
        'Warehouse Supervisor',
        'Logistics Analyst',
        'Truck Driver',
        'Warehouse Worker'
    ],
    'Government & Military': [
        'Environmental Scientist',
        'Lifeguard',
        'Zoning Manager',
        'Federal Government Worker',
        'USAR Unit Administrator',
        'Zoning Specialist',
        'Firefighter',
        'Wildlife Biologist',
        'Zoning Supervisor',
        'Grant Writer',
        'Zipsort Operator',
        'Intelligence Analyst',
        'Zoning Enforcement Inspector'
    ],
    'Marketing & Advertising & PR': [
        'Brand Manager',
        'Marketing Assistant',
        'Online Marketing Manager',
        'Copywriter',
        'Marketing Associate',
        'Product Marketing Manager',
        'Director Of Communication',
        'Marketing Coordinator',
        'Public Relations Manager',
        'Director Of Marketing',
        'Marketing Manager',
        'VP of Marketing',
        'Market Research Analyst',
        'Marketing Specialist'
    ],
    'Upper Management & Consulting': [
        'Business Analyst',
        'Business Process Analyst',
        'General Manager',
        'Business Manager',
        'Chief Financial Officer',
        'Manager',
        'Business Office Manager',
        'Director',
        'VP'
    ]
}
